version: '3.8'
name: prism

services:
  db:
    image: mysql:8.3.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: prism

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data

  redis-commander:
      image: rediscommander/redis-commander:latest
      environment:
        - REDIS_HOSTS=local:redis:6379
      ports:
        - '8082:8081'

volumes:
  redis_data: