CREATE DATABASE IF NOT EXISTS prism CHARACTER SET utf8;
CREATE USER 'prism'@'%' IDENTIFIED BY 'prism';
GRANT SELECT,INSERT,CREATE,ALTER,DROP,LOCK TABLES,CREATE TEMPORARY TABLES, DELETE,UPDATE,EXECUTE ON prism.* TO 'prism'@'%';