with-expecter: true
all: true
recursive: true
outpkg: 'mocks'
dir: 'mocks'
packages:
  bearded-proxy/proxy/config:
    interfaces:
      AppConfig:
  bearded-proxy/proxy/repository:
    interfaces:
      ProxyRepository:
